name: python test
on: [push]

env:
  GO_VERSION: 1.22.0

jobs:
  python-test:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        platform: [ubuntu-latest, windows-latest, macos-latest, macos-13]
    steps:
      - name: git clone
        uses: actions/checkout@v4

      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Python unit tests
        run: python -m unittest
        working-directory: src

      # There appears to be a bug around
      # `nextmv-io/sdk@v1.8.0/golden/file.go:75` specifically in Windows. When
      # attempting to remove a temp file, the following error is encountered:
      # `panic: remove C:\Users\RUNNER~1\AppData\Local\Temp\output1368198263:
      # The process cannot access the file because it is being used by another
      # process.` We need to figure out why it only happens in Windows. Until
      # then, we will not run the golden file tests in Windows.
      # Source:https://github.com/nextmv-io/nextroute/actions/runs/11414952328/job/31764458969?pr=65
      - name: set up Go
        if: ${{ matrix.platform != 'windows-latest' }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golden file tests from Python package
        if: ${{ matrix.platform != 'windows-latest' }}
        run: go test $(go list ./... | grep github.com/nextmv-io/nextroute/src)
